name = "MaterialSimulations"
uuid = "00000000-0000-0000-0000-000000000000"
version = "0.1.0"
authors = ["Daniel Miles <danielmiles@vt.edu>"]
description = "Material simulations research: mass-spring lattice systems with exponential springs"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.9"

